function [ax,hlines] = plotyyyerrorbar(xx,ymean1,ymean2,ymean3,ysem1,ysem2,ysem3,ylabels)

%PLOTYYY - Extends plotyy to include a third y-axis
%          Can be used to plot errorbars
%Syntax:  [ax,hlines] = plotyyy(x1,y1,x2,y2,x3,y3,ylabels)
%
%Inputs: x1,y1 are the xdata and ydata for the first axes' line
%        x2,y2 are the xdata and ydata for the second axes' line
%        x3,y3 are the xdata and ydata for the third axes' line
%        ylabels is a 3x1 cell array containing the ylabel strings
%
%Outputs: ax -     3x1 double array containing the axes' handles
%         hlines - 3x1 double array containing the lines' handles
%
%Example:
%x=0:10;
%y1=x;  y2=x.^2;   y3=x.^3;
%ylabels{1}='First y-label';
%ylabels{2}='Second y-label';
%ylabels{3}='Third y-label';
%[ax,hlines] = plotyyy(x,y1,x,y2,x,y3,ylabels);
%legend(hlines, 'y = x','y = x^2','y = x^3',2)
%
%m-files required: none
%Author: Denis Gilbert, Ph.D., physical oceanography
%Maurice Lamontagne Institute
%Dept. of Fisheries and Oceans Canada
%email: gilbertd@dfo-mpo.gc.ca
%Web: http://www.qc.dfo-mpo.gc.ca/iml/
%April 2000; Last revision: 14-Nov-2001

if nargin==6
    %Use empty strings for the ylabels
    ylabels{1}=' '; ylabels{2}=' '; ylabels{3}=' ';
elseif nargin > 8
    error('Too many input arguments')
elseif nargin < 7
    error('Not enough input arguments')
end

%%
figure('units','normalized',...
    'DefaultAxesXMinorTick','off','DefaultAxesYminorTick','off');

%Plot the first two lines with plotyy
fun1 = @(x,y) errorbar(x,y,ysem1);
fun2 = @(x,y) errorbar(x,y,ysem2);

[ax, hlines(1),hlines(2)] = plotyy(xx,ymean1,xx,ymean2,fun1,fun2);

xlabel('$L_c$ (cm)','Interpreter','latex')
set(ax(1),'ycolor','k')
set(ax(2),'ycolor','b')
set(ax(2),'FontSize',20)
set(ax(2),'TickLabelInterpreter','latex')
set(hlines(1),'LineStyle','--','Marker','o','MarkerSize',8,'Color','k','MarkerFaceColor','k')
set(hlines(2),'LineStyle','--','Marker','d','MarkerSize',8,'Color','b','MarkerFaceColor','b')
cfig = get(gcf,'color');
set(ax(1),'TickLabelInterpreter','latex','TickDir','out')
set(ax(2),'TickLabelInterpreter','latex','TickDir','out')
set(gca,'FontSize',20)
set(get(ax(1),'ylabel'),'string',ylabels{1},'Interpreter','latex','FontSize',20)
set(get(ax(2),'ylabel'),'string',ylabels{2},'Interpreter','latex','FontSize',20)

pos = [0.1  0.1  0.7  0.8];
offset = pos(3)/4.5; % Increase denominator to reduce offset
%Reduce width of the two axes generated by plotyy
pos(3) = pos(3) - offset/2;
set(ax,'position',pos);
%Determine the position of the third axes
pos3=[pos(1) pos(2) pos(3)+offset pos(4)];
%Determine the proper x-limits for the third axes
limx1=get(ax(1),'xlim');
limx3=[limx1(1)   limx1(1) + 1.2*(limx1(2)-limx1(1))];
%Bug fix 14 Nov-2001: the 1.2 scale factor in the line above
%was contributed by Mariano Garcia (BorgWarner Morse TEC Inc)
ax(3)=axes('Position',pos3,'box','off',...
    'Color','none','XColor','k','YColor','r',...
    'xtick',[],'xlim',limx3,'yaxislocation','right','FontSize',20);
set(ax(3),'TickLabelInterpreter','latex','TickDir','out')
% hlines(3) = line(x3,y3,'Color','r','Parent',ax(3));
hlines(3) = errorbar(xx,ymean3,ysem3,'Parent',ax(3));
set(ax(3),'ycolor','r')
set(ax(3),'yaxislocation','right')
set(ax(3),'XTickLabel',[]);
set(ax(3),'xtick',[])
alpha clear
set(hlines(3),'LineStyle','--','Marker','d','MarkerSize',8,'Color','r','MarkerFaceColor','r')
limy3=get(ax(3),'YLim');
set(gca,'TickLabelInterpreter','latex')
set(gca,'FontSize',20)
set(ax(3),'ycolor','r')
cfig = get(gcf,'color');
ax(3).Visible = 'off';
line([limx1(2) limx3(2)],[limy3(1) limy3(1)],...
    'Color',cfig,'Parent',ax(3),'Clipping','off');
axes(ax(2))
set(gca,'TickLabelInterpreter','latex')
set(gca,'FontSize',20)
ax(3)=axes('Position',pos3,'box','off',...
    'Color','none','XColor','r','YColor','r',...
    'xtick',[],'xlim',limx3,'yaxislocation','right','FontSize',20);
set(gca,'TickLabelInterpreter','latex')
set(ax(3),'TickLabelInterpreter','latex','TickDir','out')

ylim([-10 80])

%Label third y-axis

set(get(ax(3),'ylabel'),'string',ylabels{3},'Interpreter','latex','FontSize',20)
