%% Use this figure to write and rotate an annotation box

function createfigure
%CREATEFIGURE

%  Auto-generated by MATLAB on 15-Dec-2021 13:02:43

% Create figure
figure;


t=text(0.5,0.5,'Button Label','Rotation',90,'FontSize',14)
end

